spring:
  application:
    name: testovich
  datasource:
    url: jdbc:postgresql://localhost/название базы
    username: имя юзера базы
    password: пароль
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: че-то длинное
server:
  port: 8090